language: ruby
sudo: required
services:
  - docker
rvm:
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
bundler_args: "--jobs=4 --retry=3"
cache: bundler
before_install:
  - gem update --system --no-document
  - gem install bundler --no-document
script:
  - bundle exec rake spec
notifications:
  email: false
matrix:
  allow_failures:
  - rvm: ruby-head
